/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPushSendRouteImport } from './routes/api/public/push/send'
import { Route as ApiPublicPushVapidKeyRouteImport } from './routes/api/public/push/vapid-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSendRoute = ApiPublicPushSendRouteImport.update({
  id: '/api/public/push/send',
  path: '/api/public/push/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushVapidKeyRoute = ApiPublicPushVapidKeyRouteImport.update({
  id: '/api/public/push/vapid-key',
  path: '/api/public/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/push/send' | '/api/public/push/vapid-key'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/push/send' | '/api/public/push/vapid-key'
  id: '__root__' | '/' | '/api/public/push/send' | '/api/public/push/vapid-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPushSendRoute: typeof ApiPublicPushSendRoute
  ApiPublicPushVapidKeyRoute: typeof ApiPublicPushVapidKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/send': {
      id: '/api/public/push/send'
      path: '/api/public/push/send'
      fullPath: '/api/public/push/send'
      preLoaderRoute: typeof ApiPublicPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/vapid-key': {
      id: '/api/public/push/vapid-key'
      path: '/api/public/push/vapid-key'
      fullPath: '/api/public/push/vapid-key'
      preLoaderRoute: typeof ApiPublicPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPushSendRoute: ApiPublicPushSendRoute,
  ApiPublicPushVapidKeyRoute: ApiPublicPushVapidKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
